server:
  port: 80

spring:
  datasource:
    username: root
    password: wsy
    url: jdbc:mysql://120.78.190.233:3306/api-gateway?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/config/mybatis-config.xml

